### PR TITLE
Update to CPython 3.12.4.

### PR DESCRIPTION
**Pull request by kpfleming**

### CODE REVIEW

**Comment by kpfleming** [comment]
@zanieb @charliermarsh This one is ready for yesterday's release of CPython 3.12.4.

**Review by indygreg — APPROVED** [review]
This looks good. Thanks for the contribution!

CI is busted. Looks unrelated. I'm away from my computer for a few days and am not able to debug. We'll need CI passing to release. So no sense merging this until CI is unbroken.

**Comment by charliermarsh** [comment]
It might be transient? I'll retry the failed jobs.

**Comment by kpfleming** [comment]
Yeah, the failures are various forms of network errors, not related to the PR's content.

**Comment by charliermarsh** [comment]
Thanks @kpfleming.

**Pull request merged**
