### PR TITLE
Bump to CPython 3.8.19, 3.9.19, and 3.10.14

### PR DESCRIPTION
**Pull request by charliermarsh**
See: https://github.com/indygreg/python-build-standalone/issues/244.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Marking as draft while I look at failures.

**Comment by charliermarsh** [comment]
Oh, I forgot to update the sizes (only the SHAs). My bad.

**Comment by charliermarsh** [comment]
For posterity, I've been using:

```shell
shasum -a 256 musl-1.2.4.tar.gz
stat -f%z musl-1.2.4.tar.gz
```

**Comment by charliermarsh** [comment]
I'm seeing [here](https://github.com/indygreg/python-build-standalone/actions/runs/8511394376/job/23311193408?pr=246#step:7:8134):

```text
Traceback (most recent call last):
  File "/home/runner/work/python-build-standalone/python-build-standalone/cpython-unix/build.py", line 1217, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/runner/work/python-build-standalone/python-build-standalone/cpython-unix/build.py", line 1073, in main
    simple_build(
  File "/home/runner/work/python-build-standalone/python-build-standalone/cpython-unix/build.py", line 239, in simple_build
    archive = download_entry(entry, DOWNLOADS_PATH)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/python-build-standalone/python-build-standalone/pythonbuild/utils.py", line 305, in download_entry
    download_to_path(url, local_path, entry["size"], entry["sha256"])
  File "/home/runner/work/python-build-standalone/python-build-standalone/pythonbuild/utils.py", line 292, in download_to_path
    raise Exception("download failed after multiple retries")
Exception: download failed after multiple retries
make: *** [Makefile:111: /home/runner/work/python-build-standalone/python-build-standalone/build/bdb-6.0.19-armv7-unknown-linux-gnueabi-lto.tar] Error 1
```

**Comment by charliermarsh** [comment]
Must've been a transient failure.

**Review by zanieb — APPROVED** [review]

**Review by indygreg — APPROVED** [review]
And it looks like 3.11.9 and 3.12.3 are out now as well. So we should bump those and get a release out as soon as logistically possible.

**Comment by charliermarsh** [comment]
Sounds good, I can do that now.

**Comment by charliermarsh** [comment]
Added in https://github.com/indygreg/python-build-standalone/pull/249.

**Comment by charliermarsh** [comment]
Once these are merged, what's left for the release? `just release`, then publish a release from `latest-release` on completion?

**Comment by indygreg** [comment]
Yeah, in theory once everything is merged and CI on the target commit is green, you can run `just release <GitHub token> <commit> <tag>` and it does the rest.

My shell history says that the last release command was ` just release $(cat /path/to/github/token) 61ace30326ba7c32325c6633665cc571ac56b82a 20240224`.

**Pull request merged**
