### PR TITLE
Scope `libatomic` allowance to MIPS on Python 3.13

### PR DESCRIPTION
**Pull request by zanieb**
Addressing the initial feedback in https://github.com/indygreg/python-build-standalone/issues/410

### CODE REVIEW

**Review by indygreg — APPROVED** [review]
Thank you.

A proper solution here might be to statically link libatomic. But that can be done separately.

**Comment by zanieb** [comment]
Thanks for giving it a look

> A proper solution here might be to statically link libatomic. But that can be done separately.

Agreed. I've started looking into that, but after engaging upstream (https://github.com/python/cpython/issues/127708#issuecomment-2524172362) I'm starting to wonder about the value of the MIPS distributions?

**Comment by indygreg** [comment]
Let's merge this since it fixes the `PYTHON.json` metadata advertisement for `libatomic.so` on Linux (which is wrong). We can discuss MIPS elsewhere.

**Comment by indygreg** [comment]
Also, `extension-modules.yml` has the reference to `libatomic` regarding OpenSSL I was thinking ok:

```
_hashlib:
  sources:
    - _hashopenssl.c
  includes-deps:
    - include
  links:
    - crypto
  links-conditional:
    # Clang built OpenSSL 3.x depends on libatomic. We force linking against
    # a static library so there isn't a runtime dependency.
    - name: ':libatomic.a'
      targets:
        - i686-unknown-linux-gnu
        - mips-unknown-linux-gnu
        - mipsel-unknown-linux-gnu
        - x86_64.*-unknown-linux-gnu
```

We _could_ change the `build-cpython.sh` script to statically link `libatomic.a`.

**Comment by zanieb** [comment]
Yeah I was looking at that implementation to guide how to hide the symbol and force it to statically link 👍

**Pull request merged**
