### PR TITLE
Win: Use static MSVC's CRT (/MT) for all projects when target is static.

### PR DESCRIPTION
**Pull request by polkovnikov**
This pull request implements issue #37 for Win.

Both `openssl` and `cpython` builds were patched to use `/MT`.

I've tested building Py 3.7 from scratch and checked that `python.exe` and other dlls don't have dynamic CRT DLLs (`VCRUNTIME140.DLL` and others) in import table. Also compiled simple application using `Python.h` and linking static `python37.lib` from final distribution, this application also didn't have CRT's DLLs in import.

You may freely modify my changes if they are not meeting your expectations.

[Here](https://github.com/polkovnikov/python-build-standalone/releases/download/win-static-crt/cpython-3.7.7-x86_64-pc-windows-msvc-static-noopt-20200419T1048.tar.zst) I compiled 64-bit static (/MT) version for testing.

### CODE REVIEW

**Comment by mardukbp** [comment]
@polkovnikov Does this patch allow building Python 3.8.x statically? The [latest release](https://github.com/indygreg/python-build-standalone/releases/tag/20200418) of python-build-standalone states that static Windows builds of Python 3.8.x are not yet supported.

**Comment by polkovnikov** [comment]
I didn't try to build 3.8, I'll try now.

**Comment by indygreg** [comment]
I'm going to look at this today. There's a good chance I'll commit it myself after applying some changes. At the very least I'll be running `black` to reformat the files.

**Comment by indygreg** [comment]
I've made significant changes to this PR locally and will be committing the feature soon. This PR is no longer needed.

**Pull request closed without merging**
